version: '3.8'

volumes:
  db-data:

networks:
  crm-network:
    driver: bridge

services:
  # php (app)
  app:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/crm/app
    networks:
      - crm-network

  node:
    image: node:22-bookworm-slim
    volumes:
      - ./app:/var/www/crm/app
    working_dir: /var/www/crm/app
    profiles: ["cli"]
    networks:
      - crm-network

  # nginx
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - '8080:80'
      - '8082:8082'
    volumes:
      - ./app:/var/www/crm/app
      - ./frontend:/var/www/crm/frontend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - crm-network

  # MySQL
  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
      args:
        MYSQL_DATABASE: crm
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - crm-network
      
  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - crm-network